import {useEffect,useState} from 'react'
import type {PayrollService} from './payrollService'
import {defaultCompanyInfo,type CompanyInfo} from './companyInfo'
export function CompanyInfoPage({service,onNotice}:{service:PayrollService;onNotice:(s:string)=>void}){
 const [info,setInfo]=useState(defaultCompanyInfo),[error,setError]=useState('')
 useEffect(()=>{void service.companyInfo().then(setInfo)},[service])
 const labels={name:'회사명',industry:'업종',industryCode:'한국표준산업분류 코드',businessNumber:'사업자등록번호',managementNumber:'사업장관리번호',address:'소재지',representative:'대표자',telephone:'회사 대표 / 사업장 전화번호',occupationCode:'신고 기본 직종코드 (KECO 2025)'}
 return <section><h2>회사정보</h2><p>신고 파일의 전화번호에는 아래 회사 전화번호를 사용합니다. 기본값은 모두 실습용 가상정보입니다.</p><form className="panel" onSubmit={e=>{e.preventDefault();void service.saveCompanyInfo(info).then(()=>onNotice('회사정보를 저장했습니다.')).catch(e=>setError(e.message))}}><div className="formGrid three">{Object.entries(labels).map(([k,label])=><label key={k}>{label}<input required value={info[k as keyof typeof labels]??''} onChange={e=>setInfo({...info,[k]:e.target.value})}/></label>)}<label>보험구분<select value={info.insuranceCode} onChange={e=>setInfo({...info,insuranceCode:Number(e.target.value)})}><option value={1}>산재보험</option><option value={3}>고용보험</option><option value={5}>산재·고용보험</option></select></label><label>이직사유 기본값<select value={info.departureCode} onChange={e=>setInfo({...info,departureCode:Number(e.target.value)})}><option value={1}>회사 사정 / 계약기간 만료</option><option value={2}>부득이한 개인 사정</option><option value={3}>기타 개인 사정</option></select></label><label>회사 연차 운영기준<select value={info.leavePolicy} onChange={e=>setInfo({...info,leavePolicy:e.target.value as CompanyInfo['leavePolicy']})}><option value="FAVORABLE">두 기준 비교 · 근로자 유리 기준</option><option value="HIRE">입사일 기준 (법정 최소기준)</option></select></label></div><p>기본 직종·이직사유는 신고 전 실제 근로자 사정에 맞게 변경하세요. </p>{error&&<p role="alert">{error}</p>}<button className="primary">회사정보 저장</button></form><div className="panel"><h3>프로젝트 외부 계약</h3><table><thead><tr><th>성명</th><th>구분</th><th>프로젝트</th><th>계약기간</th><th>월 계약보수</th><th>소득구분</th></tr></thead><tbody>{info.externalContracts?.map(c=><tr key={c.id}><td>{c.name}</td><td>프리랜서</td><td>{c.project}</td><td>{c.startDate} ~ {c.endDate}</td><td>{c.monthlyFee.toLocaleString()}원</td><td>사업소득 · 근로자 급여 대상 제외</td></tr>)}</tbody></table></div></section>
}
