import {ScrollTable} from '../../components/ScrollTable'
import {seoulDate} from './companyInfo'
import {buildWorkReport,downloadFile} from './workReport'
import {DownloadActions} from '../../components/DownloadActions'
import { useEffect, useState, useRef } from 'react'
import type { DailyWorkRecord, DailyWorker, DailyWorkerInput, Organization } from '../../domain/types'
import { PayrollService } from './payrollService'
import { clockHours } from '../attendance/timeRules'
import { calculateDailyWorkRecord } from './dailyWorkerRules'

import {exportTable,readTable} from '../attendance/attendanceFiles'
import {dailyWorkerHeaders,dailyWorkerValues,parseDailyWorkers} from './dailyWorkerFiles'
import {dailyHeaders,dailyValues,dailyAllowanceLabels,parseDailyRows} from './dailyFiles'

const won=new Intl.NumberFormat('ko-KR')
const money=(v:number)=>`${won.format(Math.round(v))}원`
const today=()=>new Date().toISOString().slice(0,10)

export function DailyWorkerPage({service,organizations,onNotice}:{service:PayrollService;organizations:Organization[];onNotice:(m:string)=>void}){
  const [fileError,setFileError]=useState(''),[fileBusy,setFileBusy]=useState(false),[recordsView,setRecordsView]=useState(false);const masterUpload=useRef<HTMLInputElement>(null),recordsUpload=useRef<HTMLInputElement>(null)
  const [workers,setWorkers]=useState<DailyWorker[]>([])
  const [records,setRecords]=useState<DailyWorkRecord[]>([])
  const [page,setPage]=useState(0)
  const [query,setQuery]=useState('')
  const [orgId,setOrgId]=useState('ALL')
  const [from,setFrom]=useState(seoulDate().slice(0,7)+'-01')
  const [to,setTo]=useState(()=>{const month=seoulDate().slice(0,7);return `${month}-${new Date(Number(month.slice(0,4)),Number(month.slice(5)),0).getDate()}`})
  const [applied,setApplied]=useState<{from:string;to:string}|null>(null),[closed,setClosed]=useState<Record<string,string>>({})
  const reportMonth=applied?.to.slice(0,7)??to.slice(0,7)
  const [workerOpen,setWorkerOpen]=useState(false)
  const [editWorker,setEditWorker]=useState<DailyWorker|null>(null)
  const [recordWorker,setRecordWorker]=useState<DailyWorker|null>(null)
  const refresh=async()=>{setWorkers(await service.dailyWorkers());setRecords(await service.dailyWorkRecords());setClosed(await service.dailyClosedPeriods())}
  useEffect(()=>{void refresh()},[])
  const filtered=workers.filter(w=>(orgId==='ALL'||w.organizationId===orgId)&&`${w.workerNameSnapshot} ${w.workerNumber} ${w.job}`.toLowerCase().includes(query.toLowerCase()))
  const visibleWorkers=applied?filtered.filter(w=>w.startDate<=applied.to&&(!w.endDate||w.endDate>=applied.from)):[]
  const filteredRecords=records.filter(r=>filtered.some(w=>w.id===r.dailyWorkerId)&&applied&&r.workDate>=applied.from&&r.workDate<=applied.to)
  useEffect(()=>setPage(0),[applied,query,orgId])
  const fileAct=async(fn:()=>Promise<unknown>)=>{setFileBusy(true);setFileError('');try{await fn()}catch(e){setFileError((e as Error).message)}finally{setFileBusy(false)}}

  return <section>
    <div className="pageTitle"><div><h2>일용직</h2></div><button className="primary" onClick={()=>setWorkerOpen(true)}>+ 일용직 등록</button></div>
    <div className="filters dailyFilters"><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="성명, 번호, 직무 검색"/><select value={orgId} onChange={e=>setOrgId(e.target.value)}><option value="ALL">전체 조직</option>{organizations.filter(o=>o.type==='TEAM').map(o=><option key={o.id} value={o.id}>{o.name}</option>)}</select><input aria-label="조회 시작일" type="date" value={from} onChange={e=>setFrom(e.target.value)}/><input aria-label="조회 종료일" type="date" value={to} onChange={e=>setTo(e.target.value)}/><button onClick={()=>{if(!from||!to||from>to){setFileError('조회 기간을 확인하세요.');return}setApplied({from,to});setFileError('')}}>조회</button></div>
    <div className="moduleTabs"><button className={!recordsView?'active':''} onClick={()=>setRecordsView(false)}>일용직 목록</button><button className={recordsView?'active':''} onClick={()=>setRecordsView(true)}>근무·수당 목록</button></div>
    <div className="payrollActions dailyActions"><button disabled={fileBusy||!applied||!filteredRecords.some(r=>!r.confirmedAt)} onClick={()=>void fileAct(async()=>{await service.confirmRecords('daily',filteredRecords.filter(r=>!r.confirmedAt).map(r=>r.id));await refresh()})}>신고자료 확정</button><button disabled={fileBusy||!!closed[reportMonth]||!records.some(r=>r.workDate.startsWith(reportMonth))||records.some(r=>r.workDate.startsWith(reportMonth)&&!r.confirmedAt)} onClick={()=>void fileAct(async()=>{await service.closeDaily(reportMonth);await refresh()})}>{closed[reportMonth]?'마감 완료':'마감'}</button><button disabled={fileBusy||!applied} title={`${reportMonth} 신고자료`} onClick={()=>void fileAct(async()=>{const response=await fetch(new URL('work-report-template.xlsx',document.baseURI));if(!response.ok)throw new Error('신고 원본 양식을 불러올 수 없습니다.');const company=await service.companyInfo();const data=await buildWorkReport(await response.arrayBuffer(),workers,records,reportMonth,company);downloadFile(data as unknown as BlobPart,`근로내용확인신고_${reportMonth}_더미.xlsx`,'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');})}>근로내용확인신고 내보내기</button><DownloadActions name={recordsView?'일용직_근무수당':'일용직_목록'} headers={recordsView?dailyHeaders:dailyWorkerHeaders} rows={recordsView?filteredRecords.map(r=>dailyValues(workers.find(w=>w.id===r.dailyWorkerId)!,r)):visibleWorkers.map(w=>dailyWorkerValues(w,records,organizations,applied?.from??'9999-12-31',applied?.to??'0000-01-01'))} label="일용직 목록 다운로드"/><button disabled={fileBusy} onClick={()=>recordsView?recordsUpload.current?.click():masterUpload.current?.click()}>일용직 목록 업로드</button></div>
    <input ref={masterUpload} hidden type="file" accept=".xlsx,.json,.csv" onChange={e=>{const f=e.target.files?.[0];e.currentTarget.value='';if(f)void fileAct(async()=>{await service.saveDailyWorkers(parseDailyWorkers(await readTable(f),workers,organizations));await refresh();onNotice('일용직 목록 변경값을 반영했습니다.')})}}/>
    <input ref={recordsUpload} hidden type="file" accept=".xlsx,.json,.csv" onChange={e=>{const f=e.target.files?.[0];e.currentTarget.value='';if(f)void fileAct(async()=>{const data=await readTable(f);if(!data.length)throw new Error('일용직 근무·수당 자료가 없습니다.');if(data.some(r=>!workers.some(w=>w.workerNumber===String(r['번호']))))throw new Error('등록된 일용직 번호를 확인하세요.');const parsed=workers.flatMap(w=>{const group=data.filter(r=>String(r['번호'])===w.workerNumber);return group.length?parseDailyRows(group,w,records.filter(r=>r.dailyWorkerId===w.id)):[]});await service.saveDailyWorkRecords(parsed);await refresh();onNotice('일용직 근무·수당 변경값을 반영했습니다.')})}}/>
    {fileError&&<p role="alert">{fileError}</p>}
    {recordsView&&<div className="payrollActions"><button disabled={page===0} onClick={()=>setPage(page-1)}>이전</button><span>{page+1} / {Math.max(1,Math.ceil(filteredRecords.length/100))} 페이지 · {filteredRecords.length}건</span><button disabled={(page+1)*100>=filteredRecords.length} onClick={()=>setPage(page+1)}>다음</button></div>}{recordsView?<ScrollTable><table><thead><tr>{dailyHeaders.map(h=><th key={h}>{h}</th>)}<th>관리</th></tr></thead><tbody>{filteredRecords.slice(page*100,(page+1)*100).map(r=><tr className={r.confirmedAt?'confirmedRow':''} key={r.id} onClick={()=>setRecordWorker(workers.find(w=>w.id===r.dailyWorkerId)!)}>{dailyValues(workers.find(w=>w.id===r.dailyWorkerId)!,r).map((v,i)=><td key={dailyHeaders[i]}>{typeof v==='number'?v.toLocaleString('ko-KR'):v||'—'}</td>)}<td>{r.confirmedAt?<span className="confirmedMark">확정</span>:<><button>근무·수당 수기 입력</button><button onClick={e=>{e.stopPropagation();if(window.confirm('확정 후 근무·수당을 수정할 수 없습니다. 확정하시겠습니까?'))void fileAct(async()=>{await service.confirmRecords('daily',[r.id]);await refresh()})}}>신고자료 확정</button></>}</td></tr>)}</tbody></table></ScrollTable>:<ScrollTable><table><thead><tr>{dailyWorkerHeaders.map(h=><th key={h}>{h}</th>)}<th>관리</th></tr></thead><tbody>{visibleWorkers.map(w=><tr key={w.id} onClick={()=>setRecordWorker(w)}>{dailyWorkerValues(w,records,organizations,applied?.from??'9999-12-31',applied?.to??'0000-01-01').map((v,i)=><td key={dailyWorkerHeaders[i]}>{typeof v==='number'?v.toLocaleString('ko-KR'):v||'—'}</td>)}<td onClick={e=>e.stopPropagation()}><div className="inlineActions"><button className="linkButton" onClick={()=>setEditWorker(w)}>정보 수기 수정</button><button className="linkButton dangerText" onClick={()=>{if(window.confirm(`${w.workerNameSnapshot} 정보를 삭제할까요? 근무기록도 삭제됩니다.`))void service.deleteDailyWorker(w.id).then(refresh).then(()=>onNotice('일용직을 삭제했습니다.'))}}>삭제</button></div></td></tr>)}</tbody></table></ScrollTable>}
    {workerOpen&&<DailyWorkerModal organizations={organizations} onClose={()=>setWorkerOpen(false)} onSave={async(input)=>{await service.createDailyWorker(input);await refresh();setWorkerOpen(false);onNotice('일용직을 등록했습니다.')}}/>}
    {editWorker&&<DailyWorkerEditModal worker={editWorker} organizations={organizations} onClose={()=>setEditWorker(null)} onSave={async(worker)=>{await service.saveDailyWorker(worker);await refresh();setEditWorker(null);onNotice('일용직 정보를 수정했습니다.')}}/>}
    {recordWorker&&<DailyRecordModal worker={recordWorker} rows={records.filter(r=>r.dailyWorkerId===recordWorker.id)} onClose={()=>setRecordWorker(null)} onSave={async(row)=>{await service.saveDailyWorkRecord(row);await refresh();onNotice('일용 근무기록을 저장했습니다.')}} onImport={async data=>{await service.saveDailyWorkRecords(parseDailyRows(data,recordWorker,records.filter(r=>r.dailyWorkerId===recordWorker.id)));await refresh();onNotice('개인 근무기록 파일을 반영했습니다.')}} onDelete={async(id)=>{await service.deleteDailyWorkRecord(id);await refresh();onNotice('근무기록을 삭제했습니다.')}}/>}
  </section>
}

function DailyWorkerModal({organizations,onClose,onSave}:{organizations:Organization[];onClose:()=>void;onSave:(i:DailyWorkerInput)=>Promise<void>}){
  const [form,setForm]=useState<DailyWorkerInput>({name:'',birthDate:'1995-01-01',mobile:'010-0000-0000',organizationId:organizations.find(o=>o.type==='TEAM')?.id??'',job:'사무보조',status:'ACTIVE',startDate:today(),endDate:null,dailyRate:120000,bankName:'가상은행 A',accountNumberMasked:'DEMO-****-0000'})
  const [error,setError]=useState('')
  return <div className="modalBackdrop"><form className="modal wideModal" onSubmit={e=>{e.preventDefault();setError('');void onSave(form).catch(err=>setError(err instanceof Error?err.message:'저장 실패'))}}><div className="modalHead"><div><h3>일용직 등록</h3></div><button type="button" onClick={onClose}>×</button></div><div className="formGrid three"><label>성명<input value={form.name} onChange={e=>setForm({...form,name:e.target.value})} required/></label><label>생년월일<input type="date" value={form.birthDate} onChange={e=>setForm({...form,birthDate:e.target.value})}/></label><label>휴대전화<input value={form.mobile} onChange={e=>setForm({...form,mobile:e.target.value})}/></label><label>조직<select value={form.organizationId} onChange={e=>setForm({...form,organizationId:e.target.value})}>{organizations.filter(o=>o.type==='TEAM').map(o=><option key={o.id} value={o.id}>{o.name}</option>)}</select></label><label>직무<input value={form.job} onChange={e=>setForm({...form,job:e.target.value})}/></label><label>일급<input type="number" min="0" value={form.dailyRate} onChange={e=>setForm({...form,dailyRate:Number(e.target.value)})}/></label><label>근무시작<input type="date" value={form.startDate} onChange={e=>setForm({...form,startDate:e.target.value})}/></label><label>은행<input value={form.bankName} onChange={e=>setForm({...form,bankName:e.target.value})}/></label><label>가상계좌<input value={form.accountNumberMasked} onChange={e=>setForm({...form,accountNumberMasked:e.target.value})}/></label></div>{error&&<p className="formError">{error}</p>}<div className="modalActions"><button type="button" onClick={onClose}>취소</button><button className="primary">저장</button></div></form></div>
}

function DailyWorkerEditModal({worker,organizations,onClose,onSave}:{worker:DailyWorker;organizations:Organization[];onClose:()=>void;onSave:(w:DailyWorker)=>Promise<void>}){const [form,setForm]=useState(worker);const [error,setError]=useState('');return <div className="modalBackdrop"><form className="modal wideModal" onSubmit={e=>{e.preventDefault();setError('');void onSave(form).catch(err=>setError(err instanceof Error?err.message:'저장 실패'))}}><div className="modalHead"><div><h3>일용직 수정</h3><p>{worker.workerNumber}</p></div><button type="button" onClick={onClose}>×</button></div><div className="formGrid three"><label>성명<input value={form.workerNameSnapshot} disabled/></label><label>조직<select value={form.organizationId} onChange={e=>setForm({...form,organizationId:e.target.value})}>{organizations.filter(o=>o.type==='TEAM').map(o=><option key={o.id} value={o.id}>{o.name}</option>)}</select></label><label>직무<input value={form.job} onChange={e=>setForm({...form,job:e.target.value})}/></label><label>근무시작<input type="date" value={form.startDate} onChange={e=>setForm({...form,startDate:e.target.value})}/></label><label>근무종료<input type="date" value={form.endDate??''} onChange={e=>setForm({...form,endDate:e.target.value||null,status:e.target.value?'ENDED':'ACTIVE'})}/></label><label>일급<input type="number" min="0" value={form.dailyRate} onChange={e=>setForm({...form,dailyRate:Number(e.target.value)})}/></label><label>은행<input value={form.bankName} onChange={e=>setForm({...form,bankName:e.target.value})}/></label><label>가상계좌<input value={form.accountNumberMasked} onChange={e=>setForm({...form,accountNumberMasked:e.target.value})}/></label></div>{error&&<p className="formError">{error}</p>}<div className="modalActions"><button type="button" onClick={onClose}>취소</button><button className="primary">저장</button></div></form></div>}

function DailyRecordModal({worker,rows,onClose,onSave,onDelete,onImport}:{worker:DailyWorker;rows:DailyWorkRecord[];onClose:()=>void;onSave:(r:DailyWorkRecord)=>Promise<void>;onDelete:(id:string)=>Promise<void>;onImport:(data:Record<string,unknown>[])=>Promise<void>}){
  const [workDate,setWorkDate]=useState(today()),[start,setStart]=useState('09:00'),[end,setEnd]=useState('18:00'),[next,setNext]=useState(false),[pause,setPause]=useState('12:00'),[rest,setRest]=useState(60),[note,setNote]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false)
  const [allowances,setAllowances]=useState({overtimeAllowance:0,nightAllowance:0,holidayAllowance:0,otherAllowance:0})
  const [editing,setEditing]=useState<DailyWorkRecord|null>(null),[legacyHours,setLegacyHours]=useState(8);const upload=useRef<HTMLInputElement>(null)
  const legacy=editing&&!editing.startTime
  const calc=()=>({...calculateDailyWorkRecord(worker,workDate,legacy?legacyHours:clockHours(start,end,next,pause,rest,false).workedHours,note,allowances),...(!legacy?{startTime:start,endTime:end,endNextDay:next,breakStart:pause,breakMinutes:rest}:{})})
  let c:DailyWorkRecord;try{c=calc()}catch{c=calculateDailyWorkRecord(worker,workDate,0,note)}
  const sorted=rows.slice().sort((a,b)=>b.workDate.localeCompare(a.workDate))
  const act=async(fn:()=>Promise<unknown>)=>{setBusy(true);setError('');try{await fn()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
  const load=(r:DailyWorkRecord)=>{setEditing(r);setWorkDate(r.workDate);setStart(r.startTime??'09:00');setEnd(r.endTime??'18:00');setNext(r.endNextDay??false);setPause(r.breakStart??'12:00');setRest(r.breakMinutes??60);setLegacyHours(r.hours);setNote(r.note);setAllowances({overtimeAllowance:r.overtimeAllowance??0,nightAllowance:r.nightAllowance??0,holidayAllowance:r.holidayAllowance??0,otherAllowance:r.otherAllowance??0})}
  return <div className="modalBackdrop"><div className="modal wideModal dailyRecordModal" role="dialog" aria-modal="true" aria-label={`${worker.workerNameSnapshot} 근무기록`}><div className="modalHead"><div><h3>{worker.workerNameSnapshot} 근무기록</h3><p>{worker.workerNumber} · 일급 {money(worker.dailyRate)}</p></div><button onClick={onClose}>×</button></div>
  <div className="payrollActions"><DownloadActions name={`${worker.workerNameSnapshot}_근무기록`} headers={dailyHeaders} rows={sorted.map(r=>dailyValues(worker,r))} label="개인 내역 다운로드"/><button disabled={busy} onClick={()=>upload.current?.click()}>수정 파일 업로드</button><input ref={upload} type="file" hidden accept=".csv,.xlsx,.json" onChange={e=>{const f=e.target.files?.[0];e.currentTarget.value='';if(f)void act(async()=>onImport(await readTable(f)))}}/></div>

  <form onSubmit={e=>{e.preventDefault();void act(async()=>{await onSave(calc());setEditing(null);setWorkDate(today());setStart('09:00');setEnd('18:00');setNext(false);setPause('12:00');setRest(60);setNote('');setAllowances({overtimeAllowance:0,nightAllowance:0,holidayAllowance:0,otherAllowance:0})})}}><h4>{editing?'기존 근무기록 수기 수정':'근무기록 입력'}</h4><div className="formGrid three"><label>근무일<input type="date" value={workDate} disabled={!!editing} onChange={e=>setWorkDate(e.target.value)} required/></label>{legacy?<label>실근로시간 (기존 시각 미등록)<input type="number" min="0.01" max="24" step="0.01" value={legacyHours} onChange={e=>setLegacyHours(Number(e.target.value))}/></label>:<><label>출근<input type="time" value={start} onChange={e=>setStart(e.target.value)}/></label><label>퇴근<input type="time" value={end} onChange={e=>setEnd(e.target.value)}/></label><label><input type="checkbox" checked={next} onChange={e=>setNext(e.target.checked)}/>익일 퇴근</label><label>휴게 시작<input type="time" value={pause} onChange={e=>setPause(e.target.value)}/></label><label>휴게(분)<input type="number" min="0" value={rest} onChange={e=>setRest(Number(e.target.value))}/></label><label>실근로시간<input value={`${c.hours.toFixed(2)}h`} readOnly/></label></>}</div><h4>수당 별도 입력</h4><div className="formGrid three">{Object.entries(dailyAllowanceLabels).map(([k,label])=><label key={k}>{label}<input type="number" min="0" value={allowances[k as keyof typeof allowances]} onChange={e=>setAllowances({...allowances,[k]:Number(e.target.value)})}/></label>)}<label>메모<input value={note} onChange={e=>setNote(e.target.value)}/></label></div><p className="sectionNote">수당은 입력한 금액을 과세 지급액에 합산합니다. 근로시간에 따른 자동 가산수당은 별도 산정 후 입력하세요.</p><div className="resultPreview"><span>지급 {money(c.grossPay)}</span><span>소득세 {money(c.incomeTax)}</span><span>지방세 {money(c.localIncomeTax)}</span><strong>실지급 {money(c.netPay)}</strong></div><div className="modalActions">{editing&&<button type="button" onClick={()=>setEditing(null)}>수정 취소 / 신규 입력</button>}<button className="primary" disabled={busy}>근무기록 저장</button></div></form>
  {error&&<p className="formError" role="alert">{error}</p>}<ScrollTable><table><thead><tr>{dailyHeaders.map(h=><th key={h}>{h}</th>)}<th>관리</th></tr></thead><tbody>{sorted.map(r=><tr className={r.confirmedAt?'confirmedRow':''} key={r.id}>{dailyValues(worker,r).map((v,i)=><td key={dailyHeaders[i]}>{typeof v==='number'?v.toLocaleString('ko-KR'):v||'—'}</td>)}<td><button disabled={busy||!!r.confirmedAt} className="linkButton" onClick={()=>load(r)}>수기 수정</button><button disabled={busy||!!r.confirmedAt} className="linkButton" onClick={()=>void act(()=>onDelete(r.id))}>삭제</button></td></tr>)}</tbody></table></ScrollTable></div></div>
}
