import {DownloadActions} from '../../components/DownloadActions'
import {useEffect,useRef,useState} from 'react'
import type {FilingFormValues,PayrollEntry,PayrollResult,PayrollRun} from '../../domain/types'
import type {PayrollService} from './payrollService'
import {exportTable,readTable} from '../attendance/attendanceFiles'
import {PersonalDetail} from './PayrollTools'
import {EntryModal} from './PayrollEntryEditor'
import {payrollColumns,payrollHeaders,payrollValues,payrollDetail,parsePayrollRows,type PayrollRow} from './payrollColumns'
import {ManualLedger,type LedgerColumn} from './ManualLedger'
import {ScrollTable} from '../../components/ScrollTable'
export function FilingPanel({runs,service}:{runs:PayrollRun[];service:PayrollService}){
 const [view,setView]=useState<'individual'|'form'>('individual')
 const [id,setId]=useState(runs[0]?.id??''),[results,setResults]=useState<PayrollResult[]>([]),[entries,setEntries]=useState<PayrollEntry[]>([]),[detail,setDetail]=useState<PayrollRow|null>(null),[editing,setEditing]=useState<PayrollRow|null>(null),[error,setError]=useState(''),[actualRun,setActualRun]=useState<PayrollRun|null>(null);const upload=useRef<HTMLInputElement>(null)
 const refresh=async()=>{const [r,e,run]=await Promise.all([service.results(id),service.entries(id),service.run(id)]);setResults(r);setEntries(e);setActualRun(run)}
 useEffect(()=>{if(id)void refresh().catch(e=>setError(e.message))},[id,service,runs])
 const rows:PayrollRow[]=actualRun?entries.map(entry=>({run:actualRun,entry,result:results.find(r=>r.employmentId===entry.employmentId)??null})):[]
 const act=async(fn:()=>Promise<unknown>)=>{setError('');try{await fn()}catch(e){setError((e as Error).message)}}
 const formRow=actualRun?{id:actualRun.id,period:actualRun.period,payPeriod:actualRun.payDate.slice(0,7),incomeName:'상용근로소득',incomeCode:'A01',headcount:results.length,grossPay:results.reduce((s,r)=>s+r.grossPay,0),incomeTax:results.reduce((s,r)=>s+r.incomeTax,0),localIncomeTax:results.reduce((s,r)=>s+r.localIncomeTax,0),note:'중도퇴사·연말정산·비과세 신고범위 재분류 확인',...actualRun.filingFormOverrides}:null
 type FormRow=NonNullable<typeof formRow>
 const formColumns:LedgerColumn<FormRow>[]=[{label:'귀속연월',key:'period',identity:true},{label:'지급연월',key:'payPeriod',identity:true},{label:'소득구분',key:'incomeName',type:'text'},{label:'코드',key:'incomeCode',type:'text'},{label:'인원',key:'headcount',type:'number'},{label:'총지급액 대사',key:'grossPay',type:'number'},{label:'소득세',key:'incomeTax',type:'number'},{label:'지방소득세',key:'localIncomeTax',type:'number'},{label:'검토사항',key:'note',type:'text'}]
 return <><div className="moduleTabs"><button className={view==='individual'?'active':''} onClick={()=>setView('individual')}>개인별 원천세·4대보험</button><button className={view==='form'?'active':''} onClick={()=>setView('form')}>원천징수이행상황신고자료 대사</button></div><div className="filters"><select aria-label="세무 급여월" value={id} onChange={e=>setId(e.target.value)}>{runs.map(r=><option key={r.id} value={r.id}>{r.period} · {r.status}</option>)}</select></div>{view==='form'&&formRow?<><p>귀속·지급월과 소득코드를 구분하는 검토용 대사입니다. 수기 저장한 집계는 개인 급여를 변경하지 않으며 감사로그에 근거를 남깁니다.</p><ManualLedger title="원천징수이행상황신고자료 대사" rows={[formRow]} columns={formColumns} onSave={async(data,reason)=>{await service.saveFilingForm(id,data[0] as FilingFormValues,reason);await refresh()}}/></>:<><div className="payrollActions"><DownloadActions name="원천징수이행상황신고자료_대사" headers={payrollHeaders} rows={rows.map(payrollValues)} label="원천세·4대보험 목록 다운로드"/><button disabled={!actualRun||['CONFIRMED','CLOSED','PAID'].includes(actualRun.status)} onClick={()=>upload.current?.click()}>수정 파일 업로드</button><input ref={upload} type="file" hidden accept=".xlsx,.json,.csv" onChange={e=>{const file=e.target.files?.[0];e.currentTarget.value='';if(file&&actualRun)void act(async()=>{await service.saveEntries(parsePayrollRows(await readTable(file),actualRun,entries));await refresh()})}}/></div><p>표·개인 상세·파일은 급여 입력과 같은 항목 순서입니다. 개인 상세에서 원천세·보험 고지값을 수기 입력할 수 있습니다. 변경 후 급여 입력에서 재계산·검증하세요.</p><p className="sectionNote">한글 신고 입력·대사 자료이며 홈택스·공단 직접 업로드 규격은 아닙니다.</p>{error&&<p role="alert">{error}</p>}<ScrollTable><table><thead><tr>{payrollColumns.map(c=><th key={c.label}>{c.label}</th>)}</tr></thead><tbody>{rows.map(row=><tr key={row.entry.id} onClick={()=>setDetail(row)}>{payrollValues(row).map((v,i)=><td key={payrollHeaders[i]}>{typeof v==='number'?v.toLocaleString('ko-KR'):v||'—'}</td>)}</tr>)}</tbody></table></ScrollTable>{detail&&<PersonalDetail title="세무·보험 개인 상세" values={payrollDetail(detail)} onClose={()=>setDetail(null)} onEdit={!['CONFIRMED','CLOSED','PAID'].includes(detail.run.status)?()=>{setEditing(detail);setDetail(null)}:undefined}/>}{editing&&<EntryModal run={editing.run} entry={editing.entry} result={editing.result} onClose={()=>setEditing(null)} onSave={async input=>{await service.saveEntry(input);await refresh();setEditing(null)}} onDelete={async()=>{await service.deleteEntry(editing.run.id,editing.entry.employmentId);await refresh();setEditing(null)}}/>}</>}</>
}
