import {DownloadActions} from '../../components/DownloadActions'
import {useRef,useState} from 'react'
import {readTable} from '../attendance/attendanceFiles'
import {PersonalDetail} from './PayrollTools'
export type LedgerColumn<T>={label:string;key?:keyof T;read?:(row:T)=>string|number|null;type?:'number'|'text'|'date';nullable?:boolean;identity?:boolean;readonly?:boolean}
export function ledgerValues<T>(row:T,columns:LedgerColumn<T>[]){return columns.map(c=>c.read?c.read(row):row[c.key!] as string|number|null)}
export function parseLedgerRows<T extends {id:string}>(data:Record<string,unknown>[],columns:LedgerColumn<T>[],existing:T[]):T[]{
 if(!data.length)throw new Error('자료가 없습니다.');const seen=new Set<string>()
 return data.map((r,i)=>{if(columns.some(c=>!(c.label in r)))throw new Error(`${i+2}행: 화면과 같은 필수 열을 유지하세요.`);const identities=columns.filter(c=>c.identity);if(!identities.length)throw new Error('개인 식별 열이 없습니다.');const old=existing.find(e=>identities.every(c=>String(c.read?c.read(e):e[c.key!])===String(r[c.label])));if(!old)throw new Error(`${i+2}행: 개인·기간을 확인하세요.`);if(seen.has(old.id))throw new Error('중복된 개인·기간입니다.');seen.add(old.id);const next={...old};for(const c of columns){if(!c.key||c.readonly||c.identity)continue;const raw=r[c.label];let value:unknown;if(c.type==='number'){if(raw===''&&c.nullable)value=null;else{if(raw===''||raw==null||typeof raw==='boolean'||typeof raw==='object'||!Number.isFinite(Number(raw)))throw new Error(`${i+2}행: ${c.label}은 숫자로 입력하세요.`);value=Number(raw)}}else value=String(raw??'');Object.assign(next,{[c.key]:value})}return next})
}
export function ManualLedger<T extends {id:string}>({title,rows,columns,onSave,onCalculate,onConfirm}:{onCalculate?:(row:T)=>Promise<void>;onConfirm?:(rows:T[])=>Promise<void>;title:string;rows:T[];columns:LedgerColumn<T>[];onSave:(rows:T[],reason:string)=>Promise<void>}){
 const [draft,setDraft]=useState<T|null>(null),[reason,setReason]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[detail,setDetail]=useState<T|null>(null);const upload=useRef<HTMLInputElement>(null)
 const act=async(fn:()=>Promise<unknown>)=>{setError('');setBusy(true);try{await fn()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 const edit=(row:T)=>{if((row as {status?:string}).status==='CONFIRMED'){setError('확정된 자료는 수정할 수 없습니다.');return}setDraft({...row});setReason('');setDetail(null);setError('')}
 return <><div className="payrollActions"><button disabled={!rows.some(r=>(r as {status?:string}).status!=='CONFIRMED')} onClick={()=>{const first=rows.find(r=>(r as {status?:string}).status!=='CONFIRMED');if(first)edit(first)}}>{title} 수기 입력</button><DownloadActions name={title} headers={columns.map(c=>c.label)} rows={rows.map(r=>ledgerValues(r,columns))} disabled={busy}/><button disabled={busy} onClick={()=>upload.current?.click()}>수정 파일 업로드</button><input ref={upload} hidden type="file" accept=".xlsx,.json,.csv" onChange={e=>{const f=e.target.files?.[0];e.currentTarget.value='';if(f)void act(async()=>onSave(parseLedgerRows(await readTable(f),columns,rows),'파일 수기 정정'))}}/></div>{error&&<p role="alert">{error}</p>}<div className="tableWrap compactColumns ledgerTable"><table><thead><tr>{columns.flatMap(c=>[<th key={c.label}>{c.label}</th>,...(c.label==='상태'&&onCalculate?[<th key="estimate">추정 계산</th>]:[])])}<th>관리</th></tr></thead><tbody>{rows.map(row=><tr className={(row as {status?:string}).status==='CONFIRMED'?'confirmedRow':''} key={row.id} onClick={()=>setDetail(row)}>{ledgerValues(row,columns).flatMap((v,i)=>[<td key={columns[i].label}>{typeof v==='number'?(columns[i].label.includes('연도')?String(v):v.toLocaleString('ko-KR')):v??'—'}</td>,...(columns[i].label==='상태'&&onCalculate?[<td key="estimate"><button disabled={(row as {status?:string}).status==='CONFIRMED'} onClick={e=>{e.stopPropagation();void act(()=>onCalculate(row))}}>추정 계산</button></td>]:[])])}<td><button disabled={(row as {status?:string}).status==='CONFIRMED'} onClick={e=>{e.stopPropagation();edit(row)}}>수기 수정</button>{onConfirm&&<button disabled={(row as {status?:string}).status==='CONFIRMED'} onClick={e=>{e.stopPropagation();if(window.confirm('확정 후에는 수정할 수 없습니다. 확정하시겠습니까?'))void act(()=>onConfirm([row]))}}>확정</button>}</td></tr>)}</tbody></table></div>{detail&&<PersonalDetail title={`${title} 개인 상세`} values={Object.fromEntries(columns.map((c,i)=>[c.label,ledgerValues(detail,columns)[i]??'']))} onClose={()=>setDetail(null)} onEdit={(detail as {status?:string}).status==='CONFIRMED'?undefined:()=>edit(detail)}/>}
 {draft&&<div className="modalBackdrop"><form className="modal wideModal" role="dialog" aria-modal="true" aria-label={`${title} 수기 입력`} onSubmit={e=>{e.preventDefault();void act(async()=>{await onSave([draft],reason);setDraft(null)})}}><div className="modalHead"><h3>{title} 수기 입력</h3><button type="button" onClick={()=>setDraft(null)}>×</button></div><label>개인<select value={draft.id} onChange={e=>{const next=rows.find(r=>r.id===e.target.value);if(next)setDraft({...next})}}>{rows.filter(r=>(r as {status?:string}).status!=='CONFIRMED').map(r=><option key={r.id} value={r.id}>{columns.filter(c=>c.identity||c.label==='개인').map(c=>c.read?c.read(r):String(r[c.key!])).join(' · ')}</option>)}</select></label><div className="formGrid three">{columns.filter(c=>c.key&&!c.readonly&&!c.identity).map(c=><label key={c.label}>{c.label}<input type={c.type??'text'} step={c.type==='number'?'0.01':undefined} value={(draft[c.key!]??'') as string|number} onChange={e=>setDraft({...draft,[c.key!]:c.type==='number'?(e.target.value===''&&c.nullable?null:Number(e.target.value)):e.target.value})}/></label>)}</div><label>수정 사유<input required value={reason} onChange={e=>setReason(e.target.value)}/></label>{error&&<p role="alert">{error}</p>}<div className="modalActions"><button type="button" onClick={()=>setDraft(null)}>취소</button><button disabled={busy} className="primary">개별 적용</button></div></form></div>}</>
}
