import {useState} from 'react'
import type {EmployeeView,RetirementSettlement,YearEndTaxCase} from '../../domain/types'
import {ManualLedger,type LedgerColumn} from './ManualLedger'
const personColumns=<T extends {employmentId:string}>(employees:EmployeeView[]):LedgerColumn<T>[]=>[{label:'사번',identity:true,read:r=>employees.find(e=>e.employmentId===r.employmentId)?.employeeNumber??''},{label:'개인',read:r=>employees.find(e=>e.employmentId===r.employmentId)?.name??''}]
export function RetirementPanel({rows,employees,onSave,onCalculate,onConfirm}:{onConfirm:(rows:RetirementSettlement[])=>Promise<void>;rows:RetirementSettlement[];employees:EmployeeView[];onSave:(rows:RetirementSettlement[],reason:string)=>Promise<void>;onCalculate:(id:string)=>Promise<void>}){
 const [error,setError]=useState('')
 const records=employees.filter(e=>e.terminationDate).map(e=>rows.find(r=>r.employmentId===e.employmentId)??{id:`RET-${e.employmentId}`,employmentId:e.employmentId,calculationDate:new Date().toISOString().slice(0,10),terminationDate:e.terminationDate!,serviceDays:0,averageDailyWage:0,ordinaryDailyWage:0,appliedDailyWage:0,retirementPay:0,status:'DRAFT',ruleVersion:'MANUAL-REVIEW',note:'수기 검토용'} as RetirementSettlement)
 const columns:LedgerColumn<RetirementSettlement>[]=[...personColumns<RetirementSettlement>(employees),{label:'입사일',read:r=>employees.find(e=>e.employmentId===r.employmentId)?.hireDate??''},{label:'퇴직일',key:'terminationDate',readonly:true},{label:'계산일',key:'calculationDate',type:'date'},{label:'계속근로일',key:'serviceDays',type:'number'},{label:'평균일임금',key:'averageDailyWage',type:'number'},{label:'통상일임금',key:'ordinaryDailyWage',type:'number'},{label:'적용일임금',key:'appliedDailyWage',type:'number'},{label:'퇴직급여',key:'retirementPay',type:'number'},{label:'상태',key:'status',readonly:true},{label:'계산근거',key:'note',type:'text'}]
 return <><p>퇴직정산 입력·수정값은 검토용 초안으로 저장합니다. 법정 최종액은 실제 임금·제외기간 증빙으로 확인하세요.</p>{error&&<p role="alert">{error}</p>}<ManualLedger title="퇴직정산" rows={records} columns={columns} onSave={onSave} onCalculate={r=>onCalculate(r.employmentId)} onConfirm={onConfirm}/></>
}
export function YearEndPanel({rows,employees,onSave,onConfirm}:{onConfirm:(rows:YearEndTaxCase[])=>Promise<void>;rows:YearEndTaxCase[];employees:EmployeeView[];onSave:(rows:YearEndTaxCase[],reason:string)=>Promise<void>}){
 const [year,setYear]=useState(new Date().getFullYear())
 const records=employees.map(e=>rows.find(r=>r.employmentId===e.employmentId&&r.taxYear===year)??{id:`YET-${e.employmentId}-${year}`,employmentId:e.employmentId,taxYear:year,grossPay:0,incomeTaxWithheld:0,localTaxWithheld:0,basicDeductionCount:1,childCount:0,status:'DRAFT',estimatedFinalTax:null,settlementAmount:null,ruleVersion:'MANUAL-REVIEW'} as YearEndTaxCase)
 const columns:LedgerColumn<YearEndTaxCase>[]=[{label:'귀속연도',key:'taxYear',identity:true},...personColumns<YearEndTaxCase>(employees),{label:'총급여',key:'grossPay',type:'number'},{label:'기납부 소득세',key:'incomeTaxWithheld',type:'number'},{label:'기납부 지방소득세',key:'localTaxWithheld',type:'number'},{label:'기본공제인원',key:'basicDeductionCount',type:'number'},{label:'자녀',key:'childCount',type:'number'},{label:'최종 소득세 입력',key:'estimatedFinalTax',type:'number',nullable:true},{label:'정산액',key:'settlementAmount',type:'number',readonly:true,nullable:true},{label:'상태',key:'status',readonly:true}]
 return <><label>연말정산 귀속연도<input type="number" min="1900" max="2100" value={year} onChange={e=>setYear(Number(e.target.value))}/></label><p>최종 소득세를 수기 입력하면 기납부 소득세와의 차액으로 정산액을 계산합니다. 저장 후 확정 버튼으로 편집을 잠글 수 있습니다.</p><ManualLedger key={year} title="연말정산" rows={records} columns={columns} onSave={onSave} onConfirm={onConfirm}/></>
}
