import type {AttendanceDailyRecord,EmployeeView} from '../../domain/types'
import {activityLabels,calculateAttendanceDay} from './timeRules'
export const attendanceDailyHeaders=['사번','개인','근무일','상태','시작','종료','익일종료','휴게시작','휴게분','휴일근로','구간휴가','휴가시작','휴가종료','휴가익일종료','실근로시간','연장시간','야간시간','휴일시간','연차시간','수정사유','급여처리','기타메모','첨부파일 목록']
export function attendanceDailyValues(r:AttendanceDailyRecord,employees:EmployeeView[]){const e=employees.find(e=>e.employmentId===r.employmentId);return [e?.employeeNumber??'',e?.name??'',r.workDate,activityLabels[r.activity??(r.absence?'ABSENT':'WORK')],r.startTime,r.endTime,r.endNextDay?1:0,r.breakStart,r.breakMinutes,r.holiday?1:0,r.nonWorkKind?activityLabels[r.nonWorkKind]:'',r.nonWorkStartTime??'',r.nonWorkEndTime??'',r.nonWorkNextDay?1:0,r.workedHours,r.overtimeHours,r.nightHours,r.holidayHours,r.leaveHours??0,r.editReason,r.payTreatment==='UNPAID'?'무급':r.payTreatment==='BENEFIT'?'고용보험 급여':'유급',r.note??'',r.attachments?.map(f=>f.name).join(' / ')??'']}
export function parseAttendanceDaily(data:Record<string,unknown>[],employees:EmployeeView[]):AttendanceDailyRecord[]{
 if(!data.length)throw new Error('일별 근태 자료가 없습니다.')
 return data.map((r,i)=>{const e=employees.find(e=>e.employeeNumber===String(r['사번']));if(!e||e.name!==String(r['개인']))throw new Error(`${i+2}행: 사번·개인을 확인하세요.`);const activity=Object.entries(activityLabels).find(([,v])=>v===r['상태'])?.[0] as AttendanceDailyRecord['activity'];if(!activity)throw new Error('상태를 확인하세요.');const nonWorkKind=Object.entries(activityLabels).find(([k,v])=>['ANNUAL_LEAVE','OFF','SICK'].includes(k)&&v===r['구간휴가'])?.[0] as AttendanceDailyRecord['nonWorkKind'];if(r['구간휴가']&&!nonWorkKind)throw new Error('구간휴가를 확인하세요.')
 const num=(v:unknown,label:string)=>{if(v===''||v==null||typeof v==='boolean'||typeof v==='object'||!Number.isFinite(Number(v))||Number(v)<0)throw new Error(`${label} 숫자를 확인하세요.`);return Number(v)}
 const flag=(v:unknown,label:string)=>{const n=num(v,label);if(n!==0&&n!==1)throw new Error(`${label}은 0 또는 1을 입력하세요.`);return n===1}
 const row={id:'',employmentId:e.employmentId,workDate:String(r['근무일']),activity,startTime:String(r['시작']),endTime:String(r['종료']),endNextDay:flag(r['익일종료'],'익일종료'),breakStart:String(r['휴게시작']),breakMinutes:num(r['휴게분'],'휴게분'),holiday:flag(r['휴일근로'],'휴일근로'),absence:activity==='ABSENT',nonWorkKind,nonWorkStartTime:nonWorkKind?String(r['휴가시작']):undefined,nonWorkEndTime:nonWorkKind?String(r['휴가종료']):undefined,nonWorkNextDay:nonWorkKind?flag(r['휴가익일종료'],'휴가익일종료'):false,payTreatment:r['급여처리']==='무급'?'UNPAID' as const:r['급여처리']==='고용보험 급여'?'BENEFIT' as const:'PAID' as const,note:String(r['기타메모']??''),updatedAt:'',updatedBy:'HR_ADMIN',editReason:String(r['수정사유']??'')}
 return {...row,...calculateAttendanceDay(row)}
 })
}
