import { useRef, useState } from 'react'
import type { EmployeeView, DatabaseExport } from '../domain/types'
import type { HrService } from '../modules/core-hr/hrService'
import type { PayrollService } from '../modules/payroll/payrollService'
import { columns, attendanceRows, exportTable, parseAttendance, readTable, downloadBlob, type FileFormat } from '../modules/attendance/attendanceFiles'
export function DataToolbar({attendance,employees,hr,payroll,onImported,onNotice,onReset}:{attendance:boolean;employees:EmployeeView[];hr:HrService;payroll:PayrollService;onImported:()=>Promise<void>;onNotice:(s:string)=>void;onReset:()=>Promise<void>}){
  const [format,setFormat]=useState<FileFormat>('xlsx');const [open,setOpen]=useState(false);const [sample,setSample]=useState(false);const [busy,setBusy]=useState(false);const ref=useRef<HTMLInputElement>(null)
  const act=async(fn:()=>Promise<void>)=>{setBusy(true);try{await fn()}catch(e){onNotice((e as Error).message)}finally{setBusy(false)}}
  const output=async(format:FileFormat)=>{
    if(attendance){const rows=await payroll.attendance();let data=attendanceRows(rows,employees);if(sample)data=data.slice(0,3);await exportTable(sample?'근태_입력_샘플':'근태_내보내기',columns,data,format)}
    else {const db=await hr.exportDatabase();if(format==='json')downloadBlob(new Blob([JSON.stringify(db,null,2)],{type:'application/json'}),'인사_전체백업.json');else{const records:unknown[][]=[['백업정보','metadata',JSON.stringify({schemaVersion:db.schemaVersion,exportedAt:db.exportedAt})]];for(const [name,values] of Object.entries(db.data)){for(const row of Array.isArray(values)?values:[values])records.push([name,row.id,JSON.stringify(row)])}await exportTable('인사_전체백업',['자료종류','번호','자료JSON'],records,format)}}
    setOpen(false);setSample(false);onNotice('파일을 다운로드했습니다.')
  }
  const input=async(file:File)=>{
    if(attendance){const existing=await payroll.attendance();const data=parseAttendance(await readTable(file),employees,existing);if(!window.confirm(`${data.length}건의 근태를 가져오시겠습니까? 해당 월 급여 계산·검증을 다시 진행해야 합니다.`))return;await payroll.saveAttendanceBatch(data,[],data.map(r=>r.editReason).filter(Boolean).join('; ')||'파일 가져오기')}
    else{let payload:DatabaseExport;if(file.name.endsWith('.json'))payload=JSON.parse(await file.text());else{const rows=await readTable(file);const meta=rows.find(r=>r['자료종류']==='백업정보');if(!meta)throw new Error('전체 백업 형식이 아닙니다. 근태 파일은 근태 화면에서 가져오세요.');const info=JSON.parse(String(meta['자료JSON']));const data:Record<string,unknown>={};for(const r of rows){const key=String(r['자료종류']);if(key==='백업정보')continue;const item=JSON.parse(String(r['자료JSON']));if(key==='company')data[key]=item;else (data[key]??=[] as unknown[] as unknown);if(key!=='company')(data[key] as unknown[]).push(item)}payload={...info,data} as DatabaseExport}if(!window.confirm('전체 백업을 가져와 현재 실습 데이터를 교체하시겠습니까?'))return;await hr.importDatabase(payload)}
    await onImported();onNotice('데이터 가져오기를 완료했습니다.')
  }
  return <div className="toolbar"><button disabled={busy} onClick={()=>{setSample(false);setOpen(true)}}>{attendance?'근태 내보내기':'전체 백업 내보내기'}</button><button disabled={busy} onClick={()=>ref.current?.click()}>{attendance?'근태 가져오기':'전체 백업 가져오기'}</button>{attendance&&<button disabled={busy} onClick={()=>{setSample(true);setOpen(true)}}>샘플데이터 다운받기</button>}<button className="dangerGhost" onClick={()=>void act(onReset)}>교육환경 초기화</button><input ref={ref} hidden type="file" accept=".csv,.xlsx,.json" onChange={e=>{const f=e.target.files?.[0];if(f)void act(()=>input(f));e.currentTarget.value=''}}/>{open&&<div className="modalBackdrop"><div className="modal"><div className="modalHead"><h3>{sample?'근태 입력 샘플':'내보내기 형식 선택'}</h3><button onClick={()=>setOpen(false)}>×</button></div><p>{attendance?'같은 한글 열 양식으로 값을 수정해 다시 가져올 수 있습니다.':'전체 백업은 CSV·XLSX에서도 원본 관계와 값을 보존합니다. 근태 입력 파일은 근태 화면에서 내보내세요.'}</p><label>파일 형식<select value={format} onChange={e=>setFormat(e.target.value as FileFormat)}><option value="xlsx">엑셀 (.xlsx)</option><option value="csv">CSV (.csv)</option><option value="json">JSON (.json)</option></select></label><div className="modalActions"><button disabled={busy} onClick={()=>void act(()=>output(format))}>다운로드</button></div></div></div>}</div>
}
