import {applyFreeze,freezeIndex} from './tableFreeze'
import {useEffect,useState} from 'react'
function cellValue(cell:HTMLTableCellElement|undefined){if(!cell)return '';const control=cell.querySelector<HTMLInputElement|HTMLSelectElement|HTMLTextAreaElement>('input,select,textarea');return control?(control instanceof HTMLInputElement&&control.type==='checkbox'?(control.checked?'선택':'미선택'):control.value):cell.textContent??''}
export function compareCells(a:string,b:string){const number=(s:string)=>s.trim()!==''&&/^[+−\-]?[\d,.]+(?:\s*(?:원|명|일|시간|%))?$/.test(s.trim())?Number(s.replace('−','-').replace(/[^\d.\-+]/g,'')):NaN;const x=number(a),y=number(b);return Number.isFinite(x)&&Number.isFinite(y)?x-y:a.localeCompare(b,'ko',{numeric:true})}
function applyVisibility(table:HTMLTableElement){const hs=Array.from(table.tHead?.rows[0]?.cells??[]);Array.from(table.rows).filter(r=>r.parentElement?.tagName!=='THEAD').forEach(row=>{let offset=0;Array.from(row.cells).forEach(c=>{const original=Number(c.dataset.originalSpan??c.colSpan);c.dataset.originalSpan=String(original);const visible=hs.slice(offset,offset+original).filter(h=>!h.hidden).length;c.hidden=visible===0;c.colSpan=Math.max(1,visible);offset+=original})})}
export function TableControls(){
 const [active,setActive]=useState<HTMLTableElement|null>(null),[revision,setRevision]=useState(0),[menu,setMenu]=useState<{table:HTMLTableElement;index:number;x:number;y:number}|null>(null)
 const heads=(t:HTMLTableElement)=>Array.from(t.tHead?.rows[0]?.cells??[]),label=(c:HTMLTableCellElement)=>c.dataset.columnLabel??c.textContent??''
 const hide=(t:HTMLTableElement,i:number,value:boolean)=>{heads(t)[i].hidden=value;applyVisibility(t);applyFreeze(t);setRevision(v=>v+1)}
 useEffect(()=>{let frame=0;const enhance=()=>{observer.disconnect();document.querySelectorAll<HTMLElement>('.tableColumnToolbar').forEach(bar=>{const owner=(bar as HTMLElement & {ownerTable?:HTMLTableElement}).ownerTable;if(owner&&!owner.isConnected)bar.remove()});document.querySelectorAll<HTMLTableElement>('table:not(.columnChooser)').forEach(table=>{const hs=heads(table);if(!hs.length)return;hs.forEach((h,i)=>{if(h.dataset.columnLabel!==undefined)return;h.dataset.columnLabel=h.textContent?.trim()??'';const button=document.createElement('button');button.type='button';button.className='columnSort';button.textContent='▴';button.title=`${label(h)} 정렬`;button.setAttribute('aria-label',`${label(h)} 정렬`);button.onclick=e=>{e.preventDefault();e.stopPropagation();const direction=h.dataset.sortDirection==='1'?-1:1;h.dataset.sortDirection=String(direction);button.textContent=direction===1?'▴':'▾';table.dataset.sortColumn=String(i);table.dataset.sortDirection=String(direction);for(const body of Array.from(table.tBodies)){const rows=Array.from(body.rows);rows.sort((a,b)=>direction*compareCells(cellValue(a.cells[i]),cellValue(b.cells[i])));rows.forEach(row=>body.appendChild(row))}hs.forEach(c=>c.removeAttribute('aria-sort'));h.setAttribute('aria-sort',direction===1?'ascending':'descending')};h.appendChild(button);h.oncontextmenu=e=>{e.preventDefault();setMenu({table,index:i,x:e.clientX,y:e.clientY})}});if(!table.dataset.controls){table.dataset.controls='true';const bar=document.createElement('div');bar.className='tableColumnToolbar';(bar as HTMLElement & {ownerTable?:HTMLTableElement}).ownerTable=table;const button=document.createElement('button');button.type='button';button.textContent='필터';button.onclick=()=>setActive(table);bar.appendChild(button);const wrapper=table.closest('.tableWrap')??table;const create=Array.from(document.querySelectorAll<HTMLButtonElement>('.pageTitle button')).find(b=>b.textContent?.includes('+ 급여월 생성'));if(create&&!create.parentElement?.querySelector('.tableColumnToolbar')){bar.classList.add('inlineColumnToolbar');create.parentNode?.insertBefore(bar,create.nextSibling)}else wrapper.parentNode?.insertBefore(bar,wrapper)}applyVisibility(table);const sortIndex=Number(table.dataset.sortColumn);if(table.dataset.sortColumn!==undefined){for(const body of Array.from(table.tBodies)){const before=Array.from(body.rows),after=[...before].sort((a,b)=>Number(table.dataset.sortDirection)*compareCells(cellValue(a.cells[sortIndex]),cellValue(b.cells[sortIndex])));if(after.some((row,i)=>row!==before[i]))after.forEach(row=>body.appendChild(row))}}});observer.observe(document.body,{childList:true,subtree:true})};const observer=new MutationObserver(()=>{cancelAnimationFrame(frame);frame=requestAnimationFrame(enhance)});enhance();return()=>{cancelAnimationFrame(frame);observer.disconnect()}},[])
 return <>{menu&&<div className="columnContext" role="menu" style={{left:Math.min(menu.x,window.innerWidth-140),top:menu.y}}><button onClick={()=>{hide(menu.table,menu.index,true);setMenu(null)}}>숨기기</button><button onClick={()=>setMenu(null)}>닫기</button></div>}{active&&<div className="modalBackdrop" onClick={()=>setActive(null)}><div className="modal columnFilterModal" onClick={e=>e.stopPropagation()}><h3>열 필터</h3><table className="columnChooser" data-revision={revision}><thead><tr><th>항목</th><th>숨기기</th><th>숨기기 해제</th><th>틀고정</th></tr></thead><tbody>{heads(active).map((h,i)=><tr key={i}><td>{label(h)}</td><td><input type="checkbox" aria-label={label(h)+' 숨기기'} checked={h.hidden} onChange={()=>hide(active,i,true)}/></td><td><input type="checkbox" aria-label={label(h)+' 숨기기 해제'} checked={!h.hidden} onChange={()=>hide(active,i,false)}/></td><td><input type="checkbox" aria-label={label(h)+'까지 틀고정'} checked={freezeIndex(active)===i} onChange={()=>{active.dataset.freezeIndex=String(freezeIndex(active)===i?-1:i);applyFreeze(active);setRevision(v=>v+1)}}/></td></tr>)}</tbody></table><button onClick={()=>setActive(null)}>닫기</button></div></div>}</>
}
