import {demoFile} from '../../domain/attachments'
export const stages=['지원접수','서류검토','면접','처우협의','채용완료','불합격','지원철회'] as const
export type Stage=typeof stages[number]
export interface Job {id:string;title:string;team:string;count:number;closing:string;status:'작성중'|'승인대기'|'모집중'|'마감'}
export interface Candidate {documents?:import("../../domain/attachments").StoredFile[];history?:{date:string;stage:Stage}[];id:string;name:string;jobId:string;email:string;phone:string;source:string;stage:Stage;applied:string;rating:number;note:string;consent:boolean}
export interface Interview {id:string;candidateId:string;start:string;end:string;interviewer:string;location:string;status:'예정'|'완료'|'취소';note:string}
export interface Event {id:string;type:string;candidateId:string;message:string;created:string;status:'대기'|'전달완료'|'실패';error?:string}
export interface RecruitingState {jobs:Job[];candidates:Candidate[];interviews:Interview[];events:Event[];webhook:string}
export function recruitingSeed():RecruitingState {return {jobs:[{id:'JOB-1',title:'인사운영 담당자',team:'인사팀',count:2,closing:'2026-10-31',status:'모집중'},{id:'JOB-2',title:'프론트엔드 개발자',team:'개발1팀',count:3,closing:'2026-11-15',status:'승인대기'}],candidates:Array.from({length:8},(_,i)=>({id:'CAND-'+i,name:'가상지원자 '+(i+1),jobId:i%2?'JOB-2':'JOB-1',email:`candidate${i+1}@example.invalid`,phone:'000-0000-0000',source:['채용사이트','추천','직접지원'][i%3],stage:stages[i%5],applied:`2026-10-0${i%4+1}`,rating:0,note:'',consent:false,documents:[demoFile(`가상지원자_${i+1}_이력서.txt`,`HR 실습용 가상 이력서\n지원자 ${i+1}\n지원분야: ${i%2?'프론트엔드 개발':'인사운영'}\n경력: IT 서비스 프로젝트 ${i%4+1}년\n기술: ${i%2?'React, TypeScript':'인사운영, 급여, 근태'}\n실제 개인의 정보가 아닙니다.`)]})),interviews:[],events:[],webhook:''}}
export function queueEvent(state:RecruitingState,candidateId:string,type:string,message:string):RecruitingState {if(!state.candidates.some(c=>c.id===candidateId))throw new Error('지원자를 선택하세요.');return {...state,events:[...state.events,{id:crypto.randomUUID(),candidateId,type,message,created:new Date().toISOString(),status:'대기'}]}}
export function scheduleInterview(state:RecruitingState,row:Interview):RecruitingState {if(!state.candidates.some(c=>c.id===row.candidateId))throw new Error('지원자를 선택하세요.');if(!row.interviewer.trim()||!row.start||row.end<=row.start)throw new Error('면접관과 시작·종료 시간을 확인하세요.');if(state.interviews.some(i=>i.id!==row.id&&i.status==='예정'&&i.start<row.end&&i.end>row.start&&(i.interviewer===row.interviewer||i.candidateId===row.candidateId)))throw new Error('지원자 또는 면접관의 일정이 겹칩니다.');return queueEvent({...state,interviews:[...state.interviews.filter(i=>i.id!==row.id),row]},row.candidateId,'INTERVIEW_SCHEDULED',JSON.stringify(row))}
export async function deliverEvent(state:RecruitingState,id:string,send:typeof fetch=fetch):Promise<RecruitingState>{const event=state.events.find(e=>e.id===id);if(!event||event.status==='전달완료')throw new Error('전달할 대기 자료가 없습니다.');const candidate=state.candidates.find(c=>c.id===event.candidateId)!;if(!candidate.consent)throw new Error('지원자 연락·외부 연동 동의를 확인하세요.');if(!/^https:\/\//.test(state.webhook))throw new Error('HTTPS 자동화 웹훅을 연결하세요.');try{const response=await send(state.webhook,{method:'POST',headers:{'Content-Type':'application/json','Idempotency-Key':event.id},body:JSON.stringify({event,candidate,job:state.jobs.find(j=>j.id===candidate.jobId)})});if(!response.ok)throw new Error(`연동 응답 ${response.status}`);return {...state,events:state.events.map(e=>e.id===id?{...e,status:'전달완료',error:undefined}:e)}}catch(error){return {...state,events:state.events.map(e=>e.id===id?{...e,status:'실패',error:String(error)}:e)}}}
export function calendarFile(rows:Interview[],candidates:Candidate[]){const escape=(s:string)=>s.replace(/\\/g,'\\\\').replace(/\n/g,'\\n').replace(/[,;]/g,'\\$&'),stamp=(s:string)=>new Date(s).toISOString().replace(/[-:]/g,'').replace('.000','');return ['BEGIN:VCALENDAR','VERSION:2.0','PRODID:-//HR Training//ATS//KO',...rows.filter(r=>r.status!=='취소').flatMap(r=>['BEGIN:VEVENT',`UID:${r.id}@hr-training.invalid`,`DTSTAMP:${stamp(new Date().toISOString())}`,`DTSTART:${stamp(r.start)}`,`DTEND:${stamp(r.end)}`,`SUMMARY:${escape((candidates.find(c=>c.id===r.candidateId)?.name??'지원자')+' 면접')}`,`LOCATION:${escape(r.location)}`,`DESCRIPTION:${escape(r.interviewer+' '+r.note)}`,'END:VEVENT']),'END:VCALENDAR'].join('\r\n')}
