import assert from 'node:assert/strict'
import fs from 'node:fs'
import {createSeedBundle} from '../src/fixtures/seed'
import {demoDay,scenarioIds,holidays2026} from '../src/fixtures/scenarios'
import {attendanceIssue} from '../src/modules/attendance/attendanceFiles'
import {dayCounts} from '../src/app/OperationsDashboard'
import {demoFile,storeFile} from '../src/domain/attachments'
import {payrollSummary} from '../src/modules/payroll/UnifiedPayroll'
const seed=createSeedBundle(),employees=seed.employments.map(e=>({...e,employmentId:e.id,name:seed.persons.find(p=>p.id===e.personId)!.fullName,gender:seed.persons.find(p=>p.id===e.personId)!.gender})) as any,ids=scenarioIds(employees),employee=(key:string)=>employees.find((e:any)=>e.id===ids[key])
assert.equal(new Set(Object.values(ids)).size,11);assert.equal(employee('maternity').gender,'F');assert.equal(employee('spouse').gender,'M');assert.equal(employee('training').gender,'M');assert.equal(seed.employments.filter(e=>e.employmentType==='DISPATCH').length,1);assert.equal(seed.employments.filter(e=>e.employmentType==='INTERN').length,2);assert(seed.employments.every(e=>!e.hireDate.includes('NaN')&&!e.terminationDate?.includes('NaN')))
assert.equal(demoDay(employee('maternity'),'2026-01-06',ids).workedHours,6);assert.equal(demoDay(employee('maternity'),'2026-07-20',ids).activity,'MATERNITY');assert.equal(demoDay(employee('maternity'),'2026-09-16',ids).payTreatment,'PAID');assert.equal(demoDay(employee('maternity'),'2026-09-17',ids).payTreatment,'BENEFIT');assert.equal((new Date('2026-10-16').valueOf()-new Date('2026-07-19').valueOf())/86400000+1,90);assert.equal((new Date('2026-10-16').valueOf()-new Date('2026-09-01').valueOf())/86400000,45)
const sick=demoDay(employee('sick'),'2026-10-02',ids);assert.equal(sick.activity,'SICK');assert.equal(sick.payTreatment,'PAID');assert(sick.note?.includes('코로나'));assert.equal(sick.absence,false);assert.equal(demoDay(employee('unpaid'),'2026-10-02',ids).payTreatment,'UNPAID');assert.equal(demoDay(employee('absent'),'2026-10-02',ids).absence,true)
const training=demoDay(employee('training'),'2026-10-01',ids);assert.equal(training.activity,'TRAINING');assert(training.attachments?.[0].name.includes('훈련필증'));assert.equal(demoDay(employee('annual'),'2026-10-02',ids).leaveHours,8);assert.equal(demoDay(employee('family'),'2026-10-02',ids).payTreatment,'UNPAID');assert.equal(demoDay(employee('parental'),'2026-08-03',ids).activity,'PARENTAL');assert(holidays2026['2026-10-05'])
const spouse=Array.from({length:30},(_,i)=>demoDay(employee('spouse'),`2026-09-${String(i+1).padStart(2,'0')}`,ids)).filter(r=>r.activity==='SPOUSE_BIRTH');assert.equal(spouse.length,20)
const cases=Object.keys(ids).map(k=>demoDay(employee(k),'2026-10-02',ids));const counts=dayCounts(cases,'2026-10-02');assert.equal(counts.work+counts.sick+counts.annual+counts.personal+counts.weekend+counts.statutory+counts.other,counts.recorded)
assert.equal(attendanceIssue({scheduledHours:8,workedHours:0,leaveDays:0,absenceHours:0,lateMinutes:0,earlyLeaveMinutes:0,paidCreditHours:8} as any),'정상');assert(!attendanceIssue({scheduledHours:8,workedHours:0,leaveDays:0,absenceHours:0,lateMinutes:0,earlyLeaveMinutes:0,paidCreditHours:8,issueNote:'코로나 · 유급병가'} as any).includes('결근'))
const file=await storeFile(new File(['가상 이력서'], '이력서.txt',{type:'text/plain'}));assert.equal(Buffer.from(file.dataUrl.split(',')[1],'base64').toString(),'가상 이력서');assert.equal(Buffer.from(demoFile('훈련.txt','가상 필증').dataUrl.split(',')[1],'base64').toString(),'가상 필증');await assert.rejects(()=>storeFile(new File([new Uint8Array(10*1024*1024+1)],'large.txt')),/10MB/)
const summary=await payrollSummary({runs:async()=>[{id:'1',period:'2026-09'}],results:async()=>[],dailyWorkRecords:async()=>[{workDate:'2026-10-02',dailyWorkerId:'D',grossPay:10,netPay:10}]} as any);assert.deepEqual(summary.map(r=>r.period),['2026-09'])
const controls=fs.readFileSync('src/components/TableControls.tsx','utf8'),annual=fs.readFileSync('src/modules/attendance/AnnualLeavePanel.tsx','utf8'),summaryUI=fs.readFileSync('src/modules/payroll/UnifiedPayroll.tsx','utf8');assert(!controls.includes('for(const direction of [1,-1])'));assert(controls.includes('h.dataset.sortDirection'));assert(controls.includes('까지 틀고정'));assert(controls.includes('type="checkbox"'));assert(!annual.includes('법정 최소기준:'));assert(!annual.includes('비교값은'));assert(!summaryUI.includes('급여요약.xlsx 저장'))
console.log('PASS v074: exclusive sorting/freeze UI, 90-day maternity with 45 postnatal days, 20-day spouse leave, paid/unpaid sick/absence/annual/training/care, holidays, unique cases, attachment bytes/size, workforce types, summary run eligibility')
