import {summaryWorkbook} from '../src/modules/payroll/summaryExport'
import ExcelJS from 'exceljs'
import assert from 'node:assert/strict'
import 'fake-indexeddb/auto'
import {simplifiedTax} from '../src/modules/payroll/ntsTax'
import table from '../src/modules/payroll/ntsTaxTable.json'
import {calendarFile,deliverEvent,queueEvent,recruitingSeed,scheduleInterview} from '../src/modules/recruiting/recruiting'
import {compareCells} from '../src/components/TableControls'
import {IndexedDbHrRepository} from '../src/infrastructure/db/indexedDb'
assert.equal(table.length,646);for(let i=1;i<table.length;i++)assert.equal(table[i-1][1],table[i][0]);assert.equal(simplifiedTax(3000000),74350);assert.equal(simplifiedTax(3500000,4,2,'2025-09-25'),20180);assert.equal(simplifiedTax(3500000,4,2,'2026-03-01'),3510);assert.equal(simplifiedTax(3500000,4,2,'2026-02-28'),20180);assert.equal(simplifiedTax(769999),0);assert.equal(simplifiedTax(10000000),1507400);assert.equal(simplifiedTax(14000000),2904400);assert.equal(simplifiedTax(3000000,1,0,'2026-10-01',0.8),59480);assert.throws(()=>simplifiedTax(-1));assert.throws(()=>simplifiedTax(3000000,1,1));
assert(compareCells('1,000','900')>0);assert(compareCells('2026-09','2025-12')>0);assert(compareCells('사번 10','사번 2')>0);assert(compareCells('3.5일','4일')<0);assert(compareCells('−5','-2')<0)
let state=recruitingSeed();const row={id:'I1',candidateId:state.candidates[0].id,start:'2026-10-08T10:00',end:'2026-10-08T11:00',interviewer:'면접관',location:'회의실',status:'예정' as const,note:'평가 메모'};state=scheduleInterview(state,row);assert.equal(state.interviews.length,1);assert.equal(state.events.length,1);assert.throws(()=>scheduleInterview(state,{...row,id:'I2',candidateId:state.candidates[1].id}),/겹칩니다/);assert.throws(()=>scheduleInterview(state,{...row,end:row.start}),/종료/);assert(calendarFile(state.interviews,state.candidates).includes('20261008T010000Z'));assert(!calendarFile([{...row,status:'취소'}],state.candidates).includes('BEGIN:VEVENT'))
state=queueEvent(state,row.candidateId,'SMS_REQUESTED','면접 안내');await assert.rejects(()=>deliverEvent(state,state.events[1].id),/동의/);state={...state,webhook:'https://example.invalid/webhook',candidates:state.candidates.map(c=>({...c,consent:true}))};let called=0;state=await deliverEvent(state,state.events[1].id,(async(_url,request)=>{called++;assert.equal(JSON.parse(String(request?.body)).event.type,'SMS_REQUESTED');assert.equal((request?.headers as Record<string,string>)['Idempotency-Key'],state.events[1].id);return {ok:true,status:200} as Response}) as typeof fetch);assert.equal(called,1);assert.equal(state.events[1].status,'전달완료');await assert.rejects(()=>deliverEvent(state,state.events[1].id),/대기/);const failed=await deliverEvent(state,state.events[0].id,(async()=>({ok:false,status:503})) as typeof fetch);assert.equal(failed.events[0].status,'실패')
const repo=new IndexedDbHrRepository();await repo.initialize();await repo.saveRecruiting(state);assert.deepEqual(await repo.recruiting(),state);const backup=await repo.exportDatabase();assert.deepEqual(backup.data.company.recruiting,state);await repo.resetDemo();await repo.importDatabase(backup);assert.deepEqual(await repo.recruiting(),state);await repo.resetDemo();assert.equal((await repo.recruiting()).events.length,0)
console.log('PASS 646 contiguous NTS brackets, 2025/2026 child credits and pay-date boundary, withholding ratio, numeric/date sorting, interview overlap, ICS timezone/cancellation, consent, webhook acknowledgment/failure/idempotency, ATS save/reset')

const excel=await summaryWorkbook([{name:'2026년',headers:['귀속월','정규직 총인원','소득세'],rows:[['2026-02',2,20180],['2026-01',3,74350]],total:['합계',5,94530]}]);const book=new ExcelJS.Workbook();await book.xlsx.load(excel as never);const sheet=book.getWorksheet('2026년')!;assert.deepEqual(sheet.getRow(1).values.slice(1),['귀속월','정규직 총인원','소득세']);assert.equal(sheet.getCell('A2').value,'2026-02');assert.equal(sheet.getCell('B4').value,5);assert.equal(sheet.getCell('C4').value,94530);assert.equal(sheet.getRow(4).font.bold,true);assert.equal(sheet.columnCount,3);assert.equal(sheet.views[0].state,'frozen');console.log('PASS real summary Excel writer→reader: visible column order, current sort order, numeric cells, summed headcounts, year sheet, total style and freeze')
